name: build lemminx native binary
on:
  push:
    branches: [test]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        gu-binary: [gu.cmd, gu]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: windows-latest
            gu-binary: gu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Graalvm(aarch64)
        uses: DeLaGuardo/setup-graalvm@new-parameters
        with:
          graalvm: '20.2.0'
          java: 'java11'
          arch: 'amd64'
      - name: Build lemminx
        run: |
          ${{ matrix.gu-binary }} install native-image
          ./mvnw clean package -Dnative -DskipTests -Dgraalvm.static=--static
          ls org.eclipse.lemminx/target
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: releases
          path: org.eclipse.lemminx/target/*
