name: build lemminx native binary
on:
  push:
    branches: [test]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: install gu
        uses: graalvm/setup-graalvm@v1
        with:
          version: '20.2.0'
          java-version: '11'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: install static lib
        run: |
          sudo apt-get install libc6-dev
          native-image --version
      - name: Build lemminx
        run: |
          ./mvnw clean package -Dnative -DskipTests -Dgraalvm.static=--static
          ls org.eclipse.lemminx/target
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: releases
          path: org.eclipse.lemminx/target/org*
